# Generated by Django 3.1.4 on 2021-05-27 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0020_auto_20210329_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attandance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Leave', 'Leave'), ('Absent', 'Absent')], default='Present', max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('emp_attandande', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
    ]
